BOJ/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls'))
]

posts/urls.py
from django.urls import path
from django.contrib import admin
from .views import index, posts, posting, newpost, deletepost, signup
from django.contrib.auth import views as auth_views

app_name = 'posts'

urlpatterns=[
    path("admin/", admin.site.urls),
    path('', index),
    path('posts/', posts),
    path("posts/<int:pk>/", posting, name="posting"),
    path("newpost/", newpost),
    path('posts/<int:pk>/remove/', deletepost),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', signup, name='signup'),
]

posts/models.py
from django.db import models

class Post(models.Model):
    title = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    plink = models.TextField()
    code = models.TextField()
    content = models.TextField()

    def __str__(self):
        return self.title

posts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label = "email")

    class Meta:
        model = User
        fields = ("username", "email")

posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login

from .forms import UserForm
from .models import Post

import datetime as dt

def index(request):
    return render(request, 'index.html')

def posts(request):
    postlist = Post.objects.all
    return render(request, "posts.html", {"postlist":postlist})

def posting(request, pk):
    post = Post.objects.get(pk = pk)
    return render(request, "posting.html", {"post":post})

def newpost(request):
    if request.method == "POST":
        new_article = Post.objects.create(
            title = request.POST["title"],
            plink = request.POST["plink"],
            code = request.POST["code"],
            content = request.POST["content"],
        )
        return redirect("/posts/")
    return render(request, "newpost.html")

def deletepost(request, pk):
    post = Post.objects.get(pk = pk)
    if request.method == 'POST':
        post.delete()
        return redirect("/posts/")
    return render(request, 'deletepost.html', {'Post': post})

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username = username, password = raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = UserForm()
    return render(request, 'signup.html', {'form': form})

posts/templates/deletepost.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head> 
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>Test | deletepost</title>
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h2>Test Page</h2>
        <h3>deletepost.html</h3>
        
        <form method="POST">
            {% csrf_token %}
            <h3>{{Post.title}} - Delete</h3>
            <button>Delete</button>
        </form>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </body>
</html>

posts/templates/form_errors.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head> 
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>Test | form_errors</title>
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ field.label }}</strong>
                    {{ error }}
                </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}
        {% endif %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </body>
</html>

posts/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head> 
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>Test | index</title>
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">BOJ Soving</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">HOME</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/posts">POSTS</a>
                        </li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                                <a class="nav-link" href="/newpost">UPLOAD</a>
                            {% else %}
                                <a class="nav-link disabled" href="/newpost">UPLOAD</a>
                            {% endif %}
                        </li>
                    </ul>
                    <form class="d-flex">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="" style="color: #000000; padding-right: 0%;">mypage</a>
                            <a class="nav-link" href="{% url 'posts:logout' %}" style="color: #ff0000;">{{ user.username }} (LOGOUT)</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'posts:login' %}" style="color: #288f00; padding-right: 4%;">LOGIN</a>
                            <a style="color: #000000; padding: 4.5% 0%;">or</a>
                            <a class="nav-link" href="{% url 'posts:signup' %}" style="color: #288f00; padding-left: 4%;">SIGNUP</a>
                            <div style="width: 20px;"> </div>
                        {% endif %}
                    </form> 
                </div>
            </div>
        </nav>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </body>
</html>

posts/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head> 
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>Test | login</title>
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">BOJ Soving</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">HOME</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/posts">POSTS</a>
                        </li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                                <a class="nav-link" href="/newpost">UPLOAD</a>
                            {% else %}
                                <a class="nav-link disabled" href="/newpost">UPLOAD</a>
                            {% endif %}
                        </li>
                    </ul>
                    <form class="d-flex">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="" style="color: #000000; padding-right: 0%;">mypage</a>
                            <a class="nav-link" href="{% url 'posts:logout' %}" style="color: #ff0000;">{{ user.username }} (LOGOUT)</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'posts:login' %}" style="color: #288f00; padding-right: 4%;">LOGIN</a>
                            <a style="color: #000000; padding: 4.5% 0%;">or</a>
                            <a class="nav-link" href="{% url 'posts:signup' %}" style="color: #288f00; padding-left: 4%;">SIGNUP</a>
                            <div style="width: 20px;"> </div>
                        {% endif %}
                    </form> 
                </div>
            </div>
        </nav>

        {% block content %}
        <div class="row u_login_loginformtopdiv">
            <div class="col-md-4"></div>
            <div class="col-md-4 container my-3 u_login_loginformdiv">
                <form method="post" class="form-horizontal post-form" action="{% url 'posts:login' %}">
                    {% csrf_token %}
                    {% include "form_errors.html" %}
                    <div class="form-group">
                        <label for="username" class="col-sm-2 control-label">ID</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" placeholder="ID" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
                        </div>
                    </div>
                    <div class="form-group u_login_formpassword">
                        <label for="password" class="col-sm-2 control-label">PASSWORD</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" placeholder="PASSWORD" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
                        </div>
                    </div>
                    <div class="form-group u_login_formbtn">
                        <div class="row">
                            <div class="col-md-4"></div>
                            <div class="col-md-4 col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">LOGIN</button>
                            </div>
                            <div class="col-md-4"></div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-4"></div>
        </div>
        {% endblock %}
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </body>
</html>

posts/templates/newpost.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head> 
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>Test | newpost</title>
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h2>Test Page</h2>
        <h3>newpost.html</h3>

        <form method="POST">
            {% csrf_token %}
            Title<br>
            <input type="text" name="title"><br>
            Problem Link<br>
            <input type="text" name="plink"><br>
            Code<br>
            <textarea rows="100" cols="500" name="code"></textarea><br>
            Content<br>
            <textarea rows="100" cols="500" name="content"></textarea><br>
            <input type="submit" value="Upload">
        </form>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </body>
</html>

posts/templates/posting.html
{% load static %}
<!DOCTYPE html>
<html lang='ko'>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>Test | posting</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h2>Test Page</h2>
        <h3>posting.html</h3>

        <a href="/posts/">목록</a>

        <p>{{post.title}}</p>
        <p>{{post.date}}</p>
        <p>{{post.plink}}</p>
        <p>{{post.code}}</p>
        <p>{{post.content}}</p>

        <a href="/posts/{{post.pk}}/remove">Delete</a>
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </body>
</html>

posts/templates/posts.html
{% load static %} 
<!DOCTYPE html>
<html lang='ko'>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>Test | posts</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">BOJ Soving</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">HOME</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/posts">POSTS</a>
                        </li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                                <a class="nav-link" href="/newpost">UPLOAD</a>
                            {% else %}
                                <a class="nav-link disabled" href="/newpost">UPLOAD</a>
                            {% endif %}
                        </li>
                    </ul>
                    <form class="d-flex">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="" style="color: #000000; padding-right: 0%;">mypage</a>
                            <a class="nav-link" href="{% url 'posts:logout' %}" style="color: #ff0000;">{{ user.username }} (LOGOUT)</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'posts:login' %}" style="color: #288f00; padding-right: 4%;">LOGIN</a>
                            <a style="color: #000000; padding: 4.5% 0%;">or</a>
                            <a class="nav-link" href="{% url 'posts:signup' %}" style="color: #288f00; padding-left: 4%;">SIGNUP</a>
                            <div style="width: 20px;"> </div>
                        {% endif %}
                    </form> 
                </div>
            </div>
        </nav>

        <div style="margin-top:3%;"></div>
        <div class="container">
            <div class="row">
                <div class="col-1"></div>
                <div class="col">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Title</th>
                                <th scope="col">Problem</th>
                                <th scope="col">Author</th>
                            </tr>
                        </thead>
                        {% for list in postlist %}
                            <tbody>
                                <tr>
                                    <th scope="row">1</th>
                                    <td><a href="{{list.pk}}/">{{list.title}}</a></td>
                                    <td>NULL</td>
                                    <td>NULL</td>
                                </tr>
                            </tbody>
                        {% endfor %}
                      </table>
                </div>
                <div class="col-1"></div>
            </div>
        </div>
        

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </body>
</html>

posts/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head> 
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>Test | signup</title>
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">HOME</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/posts">POSTS</a>
                        </li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                                <a class="nav-link" href="/newpost">UPLOAD</a>
                            {% else %}
                                <a class="nav-link disabled" href="/newpost">UPLOAD</a>
                            {% endif %}
                        </li>
                    </ul>
                    <form class="d-flex">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="" style="color: #000000; padding-right: 0%;">mypage</a>
                            <a class="nav-link" href="{% url 'posts:logout' %}" style="color: #ff0000;">{{ user.username }} (LOGOUT)</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'posts:login' %}" style="color: #288f00; padding-right: 4%;">LOGIN</a>
                            <a style="color: #000000; padding: 4.5% 0%;">or</a>
                            <a class="nav-link" href="{% url 'posts:signup' %}" style="color: #288f00; padding-left: 4%;">SIGNUP</a>
                            <div style="width: 20px;"> </div>
                        {% endif %}
                    </form> 
                </div>
            </div>
        </nav>
        
        {% block content %}
        <div class="container my-3 u_login_loginformdiv">
            <div class="row my-3">
                <div class="col-4">
                    <h4>SignUp</h4>
                </div>
            </div>
            <form method="post" class="post-form">
                {% csrf_token %}
                {% include "form_errors.html" %}
                <div class="form-group">
                    <label for="username">username</label>
                    <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
                </div>
                <div class="form-group">
                    <label for="password1">password</label>
                    <input type="password" class="form-control" name="password1" id="password1" value="{{ form.password1.value|default_if_none:'' }}">
                </div>
                <div class="form-group">
                    <label for="password2">confirm password</label>
                    <input type="password" class="form-control" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}">
                </div>
                <div class="form-group">
                    <label for="email">email</label>
                    <input type="text" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}">
                </div>
                <button type="submit" class="btn btn-primary">create a new account</button>
            </form>
        </div>
        {% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </body>
</html>